version: '3'

services:
    backend:
        build: './backend'
        ports:
            - '8000:8000'
    
    client:
        build: 
            context: './client'
            args: 
                REACT_APP_API_URL: http://localhost:8000
        ports:
            - '8001:8001'
        depends_on: 
            - backend